services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tusharUser
      MONGO_INITDB_ROOT_PASSWORD: tusharPass
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
